### ISSUE TITLE
The Hooded Man's Name

### ISSUE THREAD

**Issue by yauhofung** [Henotis/Winter-Boot#2]
The Hooded Man claims his name is Johnny if the user chooses [Dish soap]. Therefore, the story should refer to him as Johnny for that path. Otherwise, his title will remain as Hooded Man.

NOTE: Johnny does not have to be his real name. The Hooded Man's title can change throughout the story and differ across different paths. If you're curious why I named him Johnny, watch [Real Life Math Problems](https://youtu.be/FHpQFHjcP_k) on YouTube.

**Comment by Henotis** [comment]
Fixed Johnny
